create database minitest3;
use minitest3;

CREATE TABLE VATTU
(
    MAVTU   int not null auto_increment primary key,
    TENVT   varchar(255),
    DVTINH  varchar(50),
    GIATIEN int
);

CREATE TABLE TONKHO
(
    ID_TK    INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    MAVTU_ID int,
    FOREIGN KEY (MAVTU_ID) REFERENCES VatTu (MAVTU),
    SLDAU    INT,
    TONGSLN  INT,
    TONGSLX  INT,
    SLCUOI   INT
);

CREATE TABLE NHACC
(
    MANHACC   INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TENNHACC  VARCHAR(255),
    DIACHI    VARCHAR(255),
    DIENTHOAI INT
);

CREATE TABLE DONDH
(
    SODH       INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NGAYDH     DATETIME,
    MANHACC_ID INT,
    FOREIGN KEY (MANHACC_ID) REFERENCES NHACC (MANHACC)
);

CREATE TABLE PHIEUNHAP
(
    SOPN     INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NGAYNHAP DATETIME,
    SODH_ID  INT,
    FOREIGN KEY (SODH_ID) REFERENCES DONDH (SODH)
);

CREATE TABLE PHIEUXUAT
(
    SOPX     INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NGAYXUAT DATETIME,
    TENKH    VARCHAR(255)
);

CREATE TABLE CTDONHANG
(
    SODH_ID  INT,
    FOREIGN KEY (SODH_ID) REFERENCES DONDH (SODH),
    MAVTU_ID INT,
    FOREIGN KEY (MAVTU_ID) REFERENCES VATTU (MAVTU),
    SLDAT    INT
);

CREATE TABLE CTPHIEUNHAP
(
    SOPN_ID  INT,
    FOREIGN KEY (SOPN_ID) REFERENCES PHIEUNHAP (SOPN),
    MAVTU_ID INT,
    FOREIGN KEY (MAVTU_ID) REFERENCES VATTU (MAVTU),
    SLNHAP   INT,
    DGNHAP   INT
);

CREATE TABLE CTPHIEUXUAT
(
    SOPX_ID  INT,
    FOREIGN KEY (SOPX_ID) REFERENCES PHIEUXUAT (SOPX),
    MAVTU_ID INT,
    FOREIGN KEY (MAVTU_ID) REFERENCES VATTU (MAVTU),
    SLXUAT   INT,
    DGXUAT   INT
);

INSERT INTO VATTU(TENVT, DVTINH, GIATIEN) VALUE ('CocaCola', 'Lon', 10000);
INSERT INTO VATTU(TENVT, DVTINH, GIATIEN) VALUE ('Pessi', 'Lon', 10000);
INSERT INTO VATTU(TENVT, DVTINH, GIATIEN) VALUE ('BimBim', 'Goi', 5000);
INSERT INTO VATTU(TENVT, DVTINH, GIATIEN) VALUE ('Bot Giat', 'Tui', 80000);
INSERT INTO VATTU(TENVT, DVTINH, GIATIEN) VALUE ('Tao', 'Kg', 5000);
INSERT INTO VATTU(TENVT, DVTINH, GIATIEN) VALUE ('Bo huc', 'Lon', 10000);
INSERT INTO VATTU(TENVT, DVTINH, GIATIEN) VALUE ('Bia 333', 'Lon', 10000);
INSERT INTO VATTU(TENVT, DVTINH, GIATIEN) VALUE ('My Tom', 'Goi', 3000);
INSERT INTO VATTU(TENVT, DVTINH, GIATIEN) VALUE ('Nuoc giat', 'Can', 80000);
INSERT INTO VATTU(TENVT, DVTINH, GIATIEN) VALUE ('Dua', 'Kg', 5000);

INSERT INTO TONKHO(MAVTU_ID, SLDAU, TONGSLN, TONGSLX, SLCUOI) VALUE (1, 100, 50, 60, 90);
INSERT INTO TONKHO(MAVTU_ID, SLDAU, TONGSLN, TONGSLX, SLCUOI) VALUE (2, 100, 50, 60, 90);
INSERT INTO TONKHO(MAVTU_ID, SLDAU, TONGSLN, TONGSLX, SLCUOI) VALUE (3, 200, 50, 60, 190);
INSERT INTO TONKHO(MAVTU_ID, SLDAU, TONGSLN, TONGSLX, SLCUOI) VALUE (4, 80, 50, 60, 70);
INSERT INTO TONKHO(MAVTU_ID, SLDAU, TONGSLN, TONGSLX, SLCUOI) VALUE (5, 100, 50, 60, 90);

INSERT INTO NHACC(TENNHACC, DIACHI, DIENTHOAI) VALUE ('Vin', 'Hung Yen', 0912345678);
INSERT INTO NHACC(TENNHACC, DIACHI, DIENTHOAI) VALUE ('Nha may hao hai', 'Hung Yen', 0987654321);
INSERT INTO NHACC(TENNHACC, DIACHI, DIENTHOAI) VALUE ('Nha may bia', 'Ha Noi', 0897654321);

INSERT INTO DONDH(NGAYDH, MANHACC_ID) VALUE ('2024-07-23', 1);
INSERT INTO DONDH(NGAYDH, MANHACC_ID) VALUE ('2024-07-22', 2);
INSERT INTO DONDH(NGAYDH, MANHACC_ID) VALUE ('2024-07-21', 3);

INSERT INTO PHIEUNHAP(NGAYNHAP, SODH_ID) VALUE ('2024-07-23', 1);
INSERT INTO PHIEUNHAP(NGAYNHAP, SODH_ID) VALUE ('2024-07-22', 2);
INSERT INTO PHIEUNHAP(NGAYNHAP, SODH_ID) VALUE ('2024-07-21', 3);

INSERT INTO PHIEUXUAT(NGAYXUAT, TENKH) VALUE ('2024-07-23', 'Manh');
INSERT INTO PHIEUXUAT(NGAYXUAT, TENKH) VALUE ('2024-07-23', 'Quan');
INSERT INTO PHIEUXUAT(NGAYXUAT, TENKH) VALUE ('2024-07-23', 'Nguyen');

INSERT INTO CTDONHANG(MAVTU_ID, SLDAT) VALUE (1, 10);
INSERT INTO CTDONHANG(MAVTU_ID, SLDAT) VALUE (2, 10);
INSERT INTO CTDONHANG(MAVTU_ID, SLDAT) VALUE (3, 10);
INSERT INTO CTDONHANG(MAVTU_ID, SLDAT) VALUE (4, 10);
INSERT INTO CTDONHANG(MAVTU_ID, SLDAT) VALUE (5, 10);
INSERT INTO CTDONHANG(MAVTU_ID, SLDAT) VALUE (6, 10);

SELECT *
FROM VATTU;
INSERT INTO CTPHIEUNHAP(SOPN_ID, MAVTU_ID, SLNHAP, DGNHAP) VALUE (1, 1, 20, 200000);
INSERT INTO CTPHIEUNHAP(SOPN_ID, MAVTU_ID, SLNHAP, DGNHAP) VALUE (1, 2, 20, 200000);
INSERT INTO CTPHIEUNHAP(SOPN_ID, MAVTU_ID, SLNHAP, DGNHAP) VALUE (2, 3, 20, 100000);
INSERT INTO CTPHIEUNHAP(SOPN_ID, MAVTU_ID, SLNHAP, DGNHAP) VALUE (2, 4, 20, 1600000);
INSERT INTO CTPHIEUNHAP(SOPN_ID, MAVTU_ID, SLNHAP, DGNHAP) VALUE (3, 5, 20, 100000);
INSERT INTO CTPHIEUNHAP(SOPN_ID, MAVTU_ID, SLNHAP, DGNHAP) VALUE (3, 6, 20, 200000);
INSERT INTO CTPHIEUNHAP(SOPN_ID, MAVTU_ID, SLNHAP, DGNHAP) VALUE (3, 7, 20, 200000);

INSERT INTO CTPHIEUXUAT(SOPX_ID, MAVTU_ID, SLXUAT, DGXUAT) VALUE (1, 1, 20, 200000);
INSERT INTO CTPHIEUXUAT(SOPX_ID, MAVTU_ID, SLXUAT, DGXUAT) VALUE (1, 2, 20, 200000);
INSERT INTO CTPHIEUXUAT(SOPX_ID, MAVTU_ID, SLXUAT, DGXUAT) VALUE (2, 3, 20, 100000);
INSERT INTO CTPHIEUXUAT(SOPX_ID, MAVTU_ID, SLXUAT, DGXUAT) VALUE (2, 4, 20, 1600000);
INSERT INTO CTPHIEUXUAT(SOPX_ID, MAVTU_ID, SLXUAT, DGXUAT) VALUE (3, 5, 20, 100000);
INSERT INTO CTPHIEUXUAT(SOPX_ID, MAVTU_ID, SLXUAT, DGXUAT) VALUE (3, 6, 20, 200000);
INSERT INTO CTPHIEUXUAT(SOPX_ID, MAVTU_ID, SLXUAT, DGXUAT) VALUE (3, 7, 20, 200000);

CREATE VIEW vw_CTPNHAP AS
SELECT PHIEUNHAP.SOPN     AS 'So phieu nhap hang',
       MAVTU_ID,
       CTPHIEUNHAP.SLNHAP as 'So luong',
       CTPHIEUNHAP.DGNHAP as 'Don gia',
       SLNHAP * DGNHAP    as 'Tong tien'
FROM CTPHIEUNHAP
         JOIN PHIEUNHAP ON CTPHIEUNHAP.SOPN_ID = PHIEUNHAP.SOPN;

drop view vw_CTPNHAP;
select *
from vw_CTPNHAP;

CREATE VIEW vw_CTPNHAP_VT AS
SELECT PHIEUNHAP.SOPN                          AS 'So phieu nhap',
       VATTU.MAVTU                             AS 'Ma Vat Tu',
       VATTU.TENVT                             AS 'Ten Vat Tu',
       CTPHIEUNHAP.SLNHAP                      AS 'So luong nhap',
       CTPHIEUNHAP.DGNHAP                      AS 'Don Gia',
       CTPHIEUNHAP.DGNHAP * CTPHIEUNHAP.SLNHAP AS 'Tong Tien'
FROM CTPHIEUNHAP
         JOIN PHIEUNHAP ON CTPHIEUNHAP.SOPN_ID = PHIEUNHAP.SOPN
         JOIN VATTU ON CTPHIEUNHAP.MAVTU_ID = VATTU.MAVTU;

SELECT *
FROM vw_CTPNHAP_VT;

CREATE VIEW vw_CTPNHAP_VT_PN AS
SELECT PHIEUNHAP.SOPN                          AS 'So phieu nhap',
       PHIEUNHAP.NGAYNHAP                      AS 'Ngay nhap',
       PHIEUNHAP.SODH_ID                       AS 'So don hang',
       VATTU.MAVTU                             AS 'Ma Vat Tu',
       VATTU.TENVT                             AS 'Ten Vat Tu',
       CTPHIEUNHAP.SLNHAP                      AS 'So luong nhap',
       CTPHIEUNHAP.DGNHAP                      AS 'Don Gia',
       CTPHIEUNHAP.DGNHAP * CTPHIEUNHAP.SLNHAP AS 'Tong Tien'
FROM CTPHIEUNHAP
         JOIN PHIEUNHAP ON CTPHIEUNHAP.SOPN_ID = PHIEUNHAP.SOPN
         JOIN VATTU ON CTPHIEUNHAP.MAVTU_ID = VATTU.MAVTU;

SELECT *
FROM vw_CTPNHAP_VT_PN;

CREATE VIEW vw_CTPNHAP_VT_PN_DH AS
SELECT PHIEUNHAP.SOPN                          AS 'So phieu nhap',
       PHIEUNHAP.NGAYNHAP                      AS 'Ngay nhap',
       PHIEUNHAP.SODH_ID                       AS 'So don hang',
       DONDH.MANHACC_ID                        AS 'Ma nha cung cap',
       VATTU.MAVTU                             AS 'Ma Vat Tu',
       VATTU.TENVT                             AS 'Ten Vat Tu',
       CTPHIEUNHAP.SLNHAP                      AS 'So luong nhap',
       CTPHIEUNHAP.DGNHAP                      AS 'Don Gia',
       CTPHIEUNHAP.DGNHAP * CTPHIEUNHAP.SLNHAP AS 'Tong Tien'
FROM CTPHIEUNHAP
         JOIN PHIEUNHAP ON CTPHIEUNHAP.SOPN_ID = PHIEUNHAP.SOPN
         JOIN DONDH ON PHIEUNHAP.SODH_ID = DONDH.SODH
         JOIN VATTU ON CTPHIEUNHAP.MAVTU_ID = VATTU.MAVTU;

SELECT *
FROM vw_CTPNHAP_VT_PN_DH;

CREATE VIEW vw_CTPNHAP_loc AS
SELECT *
FROM vw_CTPNHAP
WHERE `So luong` > 5;

SELECT *
FROM vw_CTPNHAP_loc;
SELECT *
FROM vw_CTPNHAP;

INSERT INTO CTPHIEUNHAP(SOPN_ID, MAVTU_ID, SLNHAP, DGNHAP) VALUE (1, 8, 4, 10000);

CREATE VIEW vw_CTPNHAP_VT_loc AS
SELECT PHIEUNHAP.SOPN                          AS 'So phieu nhap',
       VATTU.MAVTU                             AS 'Ma Vat Tu',
       VATTU.TENVT                             AS 'Ten Vat Tu',
       CTPHIEUNHAP.SLNHAP                      AS 'So luong nhap',
       CTPHIEUNHAP.DGNHAP                      AS 'Don Gia',
       CTPHIEUNHAP.DGNHAP * CTPHIEUNHAP.SLNHAP AS 'Tong Tien'
FROM CTPHIEUNHAP
         JOIN PHIEUNHAP ON CTPHIEUNHAP.SOPN_ID = PHIEUNHAP.SOPN
         JOIN VATTU ON CTPHIEUNHAP.MAVTU_ID = VATTU.MAVTU
WHERE VATTU.DVTINH LIKE 'lON';

SELECT *
FROM vw_CTPNHAP_VT_loc;

CREATE VIEW vw_CTPXUAT AS
SELECT PHIEUXUAT.SOPX                          AS 'So phieu xuat',
       CTPHIEUXUAT.MAVTU_ID                    AS 'Ma vat tu',
       CTPHIEUXUAT.SLXUAT                      AS 'So luong',
       CTPHIEUXUAT.DGXUAT                      AS 'Don gia',
       CTPHIEUXUAT.SLXUAT * CTPHIEUXUAT.DGXUAT AS 'Tong tien'
FROM CTPHIEUXUAT
         JOIN PHIEUXUAT ON CTPHIEUXUAT.SOPX_ID = PHIEUXUAT.SOPX;

SELECT *
FROM vw_CTPXUAT;

CREATE VIEW vw_CTPXUAT_VT AS
SELECT PHIEUXUAT.SOPX                          AS 'So phieu xuat',
       VATTU.MAVTU                             AS 'Ma vat tu',
       VATTU.TENVT                             AS 'Ten vat tu',
       CTPHIEUXUAT.SLXUAT                      AS 'So luong',
       CTPHIEUXUAT.DGXUAT                      AS 'Don gia',
       CTPHIEUXUAT.SLXUAT * CTPHIEUXUAT.DGXUAT AS 'Tong tien'
FROM CTPHIEUXUAT
         JOIN PHIEUXUAT ON CTPHIEUXUAT.SOPX_ID = PHIEUXUAT.SOPX
         JOIN VATTU ON CTPHIEUXUAT.MAVTU_ID = VATTU.MAVTU;

CREATE VIEW vw_CTPXUAT_VT_PX AS
SELECT PHIEUXUAT.SOPX                          AS 'So phieu xuat',
       PHIEUXUAT.TENKH                         AS 'Ten khach hang',
       VATTU.MAVTU                             AS 'Ma vat tu',
       VATTU.TENVT                             AS 'Ten vat tu',
       CTPHIEUXUAT.SLXUAT                      AS 'So luong',
       CTPHIEUXUAT.DGXUAT                      AS 'Don gia'
FROM CTPHIEUXUAT
         JOIN PHIEUXUAT ON CTPHIEUXUAT.SOPX_ID = PHIEUXUAT.SOPX
         JOIN VATTU ON CTPHIEUXUAT.MAVTU_ID = VATTU.MAVTU;

DELIMITER //

CREATE PROCEDURE sp_TongSLCuoiVatTu (IN P_MAVTU INT, OUT P_TONGSLCUOI INT)
BEGIN
    SELECT SUM(TONKHO.SLDAU + TONKHO.TONGSLN - TONKHO.TONGSLX) INTO P_TONGSLCUOI
    FROM TONKHO
        WHERE MAVTU_ID = P_MAVTU;
end //

DELIMITER ;

DROP PROCEDURE sp_TongSLCuoiVatTu;

CALL sp_TongSLCuoiVatTu(2);
SELECT @P_TONGSLCUOI;
